routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('admin')->namespace('Admin')->group(function () {
    
    Route::match(['get', 'post'], '/', 'AdminController@login');
    
    Route::group(['middleware'=>['admin']],function () {

        Route::get('dashboard', 'AdminController@index')->name('dashboard');
        Route::get('settings', 'AdminController@settings')->name('settings');
        Route::post('check_current_password', 'AdminController@checkCurrentPassword')->name('checkCurrentPassword');
        Route::post('update-current-password', 'AdminController@updateCurrentPassword')->name('updateCurrentPassword');
        Route::match(['get','post'],'update-admin-details', 'AdminController@updateAdminDetails')->name('updateAdminDetails');

        // Sections Routes
        Route::resource('sections','SectionController');

        // Brands Routes
        Route::resource('brands','BrandsController');
        Route::get('deleteBrand/{id}', 'BrandsController@deleteBrand');
        Route::patch('updateBrandStatus/{id}', 'BrandsController@updateBrandStatus');

        // Categories Routes
        Route::resource('categories', 'CategoriesController');
        Route::patch('categoryStatusUpdate/{id}', 'CategoriesController@categoryStatusUpdate');
        Route::get('getCategoryBySectionId/{id}', 'CategoriesController@getCategoryBySectionId');
        Route::get('getCategoryBySectionIdForProduct/{id}', 'CategoriesController@getCategoryBySectionIdForProduct');
        Route::get('deleteCategory/{id}', 'CategoriesController@deleteCategory');
        Route::get('deleteCategoryImage/{id}', 'CategoriesController@deleteCategoryImage');
        
        // Product Routes
        Route::resource('products', 'ProductsController');
        Route::patch('productStatusUpdate/{id}', 'ProductsController@productStatusUpdate');
        Route::get('getCategoriesBySectionId/{id}', 'ProductsController@getCategoriesBySectionId');
        Route::get('deleteProductMainImage/{id}', 'ProductsController@deleteProductMainImage');
        Route::get('deleteProductVideo/{id}', 'ProductsController@deleteProductVideo');
        Route::get('deleteProduct/{id}', 'ProductsController@deleteProduct');
        
        // Attributes Routes
        Route::resource('attributes', 'ProductAttributesController');
        Route::patch('updateAttributeStatus/{id}', 'ProductAttributesController@updateAttributeStatus');
        Route::get('deleteAttribute/{id}', 'ProductAttributesController@deleteAttribute');

        // Product Images Routes
        Route::resource('productImages', 'ProductImagesController');
        Route::patch('updateProductImageStatus/{id}', 'ProductImagesController@updateProductImageStatus');
        Route::get('deleteProductImage/{id}', 'ProductImagesController@deleteProductImage');

        Route::get('logout', 'AdminController@logout')->name('logout');
        
    });
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable =   [
        'section_id', 'brand_id', 'category_id', 'name', 'code', 'color', 'price',
        'discount', 'weight', 'main_image', 'video', 'description',
        'wash_care', 'fabric', 'pattern', 'sleeve', 'fit', 'occasion',
        'meta_title', 'meta_description', 'meta_keywords', 'is_featured',
        'status'
    ];
    
    public function section()
    {
        return $this->belongsTo(Section::class, 'section_id')->select('id','name')->where('status',1);
    }
    public function brand()
    {
        return $this->belongsTo(Brand::class, 'brand_id')->select('id','name');
    }
    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id')->select('id','name')->where('status',1);
    }
    public function attributes()
    {
        return $this->hasMany(ProductAttribute::class, 'product_id');
    }
    public function images()
    {
        return $this->hasMany(ProductImage::class, 'product_id');
    }
}

app/Http/Controllers/Admin/ProductsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Brand;
use App\Product;
use App\Section;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Session;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Session::put('page','products');
        $products = Product::with(['section','brand','category'])->where('status',1)->get();
        // $products = json_decode(json_encode($products),true);
        // echo "<pre>"; print_r($products); die;
        return view('admin.products.products')->with(compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $sections       =   Section::where('status',1)->get();
        $brands         =   Brand::where('status',1)->get();
        $categories     =   Category::where('status',1)->get();

        // Filter Arrays
        $fabrics    =   array('Cotton', 'polyester', 'Wool');
        $sleeves    =   array('Full Sleeve', 'Half Sleeve', 'Short Sleeves', 'Sleeveless');
        $patterns   =   array('Checked', 'Plain', 'Printed', 'Self', 'Solid');
        $fits       =   array('Regular', 'Slim');
        $occasions  =   array('Casual', 'Formal');
        // $categories =   Category::with('sub_categories')->select('id','name')->where('parent_id',0)->where('status',1)->get();
        return view('admin.products.add_product')->with(compact(
            'sections',
            'brands',
            'categories',
            'fabrics',
            'sleeves',
            'patterns',
            'fits',
            'occasions'
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // echo "<pre>"; print_r($request->all()); die;
        $detailsRules= [
            'section_id_for_product' => 'required',
            'brand_id_for_product' => 'required',
            'category_id_for_product' => 'required',
            'name' => 'required|max:255',
            'color' => 'required|max:255',
            'code' => 'required|alpha_num',
            'price' => 'required|numeric',
            'main_image' => 'image|mimes:jpg,jpeg,png',
            'video' => 'mimes:mp4,qt | max:10000',
        ];
        $customMessage  =   [
            'name.required' => 'Name is required',
        ];
        $this->validate($request, $detailsRules, $customMessage);

        // image update
        $isImageFileHave = 0;
        $newFileName = '';
        $fullPath = '';
        $fileLocation = 'images/product_images/large/';
        $mediumFileLocation = 'images/product_images/medium/';
        $smallFileLocation = 'images/product_images/small/';

        if($request->hasFile('main_image')){

            $getFile    =   request()->file('main_image');

            //! get file Extension
            $fileExName = request()->file('main_image')->getClientOriginalExtension();

            //! better approch for file naming with uniqid() fuction
            $newFileName = "Product_".uniqid().".".$fileExName;

            //? //* Path with File Name
            $fullPath = $fileLocation.$newFileName;
            $mediumFullPath = $mediumFileLocation.$newFileName;
            $smallFullPath = $smallFileLocation.$newFileName;

            $isImageFileHave = 1;

            //! Image Resize after stored image
            // Save Large Image
            Image::make($getFile)->fit(720, 1080, function ($constraint) {
                //$constraint->aspectRatio();
                $constraint->upsize();
            }, "top")->save($fullPath);
            // save medium image
            Image::make($getFile)->fit(360, 540, function ($constraint) {
                //$constraint->aspectRatio();
                $constraint->upsize();
            }, "top")->save($mediumFullPath);
            // save small image
            Image::make($getFile)->fit(180, 270, function ($constraint) {
                //$constraint->aspectRatio();
                $constraint->upsize();
            }, "top")->save($smallFullPath);
        }

        // Video upload
        $isVideoFileHave = 0;
        $newVideoFileName = '';
        $videoFileLocation = 'videos/product_videos/';

        if($request->hasFile('video')){

            //! get file Extension
            $videoFileExName = request()->file('video')->getClientOriginalExtension();

            //! better approch for file naming with uniqid() fuction
            // $newVideoFileName = $onlyNewVideoName."_".uniqid().".".$videoFileExName;
            $newVideoFileName = "Product_Video_".uniqid().".".$videoFileExName;

            // $resizedImage = Image::make($imageFile)->fit(590,708);
            request()->file('video')->move($videoFileLocation, $newVideoFileName);

            $isVideoFileHave = 1;
        }


        $storeProduct = Product::create([
            'section_id'    =>   $request->section_id_for_product,
            'brand_id'      =>   $request->brand_id_for_product,
            'category_id'   =>   $request->category_id_for_product,
            'name'          =>   $request->name,
            'code'          =>   $request->code,
            'color'         =>   $request->color,
            'price'         =>   $request->price,
            'discount'      =>   $request->discount==''?0:$request->discount,
            'weight'        =>   $request->weight,
            'description'   =>   $request->description,
            'main_image'    =>   $isImageFileHave==1?$newFileName:'',
            'video'         =>   $isVideoFileHave==1?$newVideoFileName:'',
            'wash_care'     =>   $request->wash_care,
            'fabric'        =>   $request->fabric,
            'pattern'       =>   $request->pattern,
            'sleeve'        =>   $request->sleeve,
            'fit'           =>   $request->fit,
            'occasion'      =>   $request->occasion,
            'meta_title'    =>   $request->meta_title,
            'meta_description'  =>   $request->meta_description,
            'meta_keywords' =>   $request->meta_keywords,
            'is_featured'   =>   $request->is_featured=='on'?'Yes':'No',
        ]);

        return redirect()->back()->with('success_message', 'Product Added successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product    = Product::where('id',$id)->first();
        $sections   = Section::where('status',1)->get();
        $brands     = Brand::where('status',1)->get();
        $categories = Category::with('sub_categories')->select('id','name')->where('section_id',$product->section_id)->where('parent_id',0)->where('status',1)->get();
        // Filter Arrays
        $fabrics    =   array('Cotton', 'polyester', 'Wool');
        $sleeves    =   array('Full Sleeve', 'Half Sleeve', 'Short Sleeves', 'Sleeveless');
        $patterns   =   array('Checked', 'Plain', 'Printed', 'Self', 'Solid');
        $fits       =   array('Regular', 'Slim');
        $occasions  =   array('Casual', 'Formal');

        if($product){
            // $product = json_decode(json_encode($product),true);
            // echo '<pre>'; print_r($product); die;
            return view('admin.products.edit_product')->with(compact('product','categories','sections','brands','fabrics','sleeves', 'patterns', 'fits', 'occasions'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // $products = json_decode(json_encode($products),true);
        // echo "<pre>"; print_r($request->all()); die;
        $getProduct    =   Product::find($id);

        $detailsRules= [
            'section_id_for_product' => 'required',
            'brand_id_for_product' => 'required',
            'category_id_for_product' => 'required',
            'name' => 'required|max:255',
            'color' => 'required|max:255',
            'code' => 'required|alpha_num',
            'price' => 'required|numeric',
            'main_image' => 'image|mimes:jpg,jpeg,png',
            'video' => 'mimes:mp4,qt | max:10000',
        ];
        $customMessage  =   [
            'name.required' => 'Name is required',
        ];
        $this->validate($request, $detailsRules, $customMessage);

        // image update
        $imageName = $getProduct->main_image;
        $isImageFileHave = 0;
        $newFileName = '';
        $fullPath = '';
        $fileLocation = 'images/product_images/large/';
        $mediumFileLocation = 'images/product_images/medium/';
        $smallFileLocation = 'images/product_images/small/';

        if($request->hasFile('main_image')){

            if($getProduct->main_image != '' || $getProduct->main_image != 'null'){
                
                $fullPath = $fileLocation.$imageName;
                $fullPathMedium = $mediumFileLocation.$imageName;
                $fullPathSmall = $smallFileLocation.$imageName;
    
                if(\File::exists($fullPath)){
        
                    \File::delete($fullPath);
                }
                if(\File::exists($fullPathMedium)){
    
                    \File::delete($fullPathMedium);
                }

resources/views/admin/products/attributes/add_attributes.blade.php
@extends('layouts.Admin.admin_layout')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Product Attributes</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ url('admin/dashboard') }}">Home</a></li>
              <li class="breadcrumb-item active">Add Product Attributes</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- SELECT2 EXAMPLE -->
            <div class="card card-default">
                <div class="card-header">
                    <h3 class="card-title">Add Product Attributes</h3>
                    <a href="{{route('products.index')}}" class="btn btn-block btn-primary" style="max-width: 150px; float: right;">All Products</a>
                    {{-- <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove">
                            <i class="fas fa-times"></i>
                        </button>
                    </div> --}}
                </div>
                <div>
                    @if (session('success_message'))
                        {{-- <div class="alert alert-success" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <strong>Success!</strong> You have been signed in successfully!
                        </div> --}}
                        <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 5px;">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            {{session('success_message')}}
                        </div>
                        @endif
                        {{-- Successful Message Alert with close and fade effect from controller --}}
                        @if (session('error_message'))
                        {{-- <div class="alert alert-success" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <strong>Success!</strong> You have been signed in successfully!
                        </div> --}}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            {{session('error_message')}}
                        </div>
                        @endif
                
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                </div>
                <!-- /.card-header -->
                <form action="{{ route('attributes.store') }}" method="post" enctype="multipart/form-data" id="attributes_form" >
                    @csrf
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="name">Product Name:</label>&nbsp;&nbsp;{{ $getProduct->name }}
                                </div>
                                <div class="form-group">
                                    <label for="code">Product Code:</label>&nbsp;&nbsp;{{ $getProduct->code }}
                                </div>
                                <div class="form-group">
                                    <label for="color">Product Color:</label>&nbsp;&nbsp;{{ $getProduct->color }}
                                </div>
                            </div>
                            <!-- /.col -->
                            <div class="col-md-6">
                                @if (!empty($getProduct->main_image) && file_exists('images/product_images/small/'.$getProduct->main_image))
                                    <img src="{{ asset('images/product_images/small/'.$getProduct->main_image)}}" width="80px" alt="product_image" />
                                @else
                                    <img src="https://via.placeholder.com/50x65" width="80px" alt="product_image" />
                                @endif
                            </div>
                            <!-- /.col -->
                            <div class="col-md-6">
                                <div class="field_wrapper">
                                    <div class="mt-2">
                                        <input type="hidden" name="product_id" value="{{$getProduct->id}}"> 
                                        <input type="text" name="size[]" id="size" placeholder="SIZE" value="" style="width: 120px;" required/>
                                        <input type="number" name="price[]" id="price" placeholder="PRICE" value="" style="width: 120px;" required/>
                                        <input type="number" name="stock[]" id="stock" placeholder="STOCK" value="" style="width: 120px;" required/>
                                        <input type="text" name="sku[]" id="sku" placeholder="SKU" value="" style="width: 120px;" required/>
                                        <a href="javascript:void(0);" class="add_button" title="Add field">&nbsp;&nbsp;Add</a>
                                    </div>
                                </div>
                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- /.row -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <button type="submit" class="btn btn-success">Add Attributes</button>
                    </div>
                </form>
            </div>
          <!-- /.card -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="container-fluid">
            <!-- SELECT2 EXAMPLE -->
            <div class="card card-default">
                <div class="card-header">
                    <h3 class="card-title">Added Attribute List</h3>
                </div>
                <form action="{{ url('/admin/attributes/'.$getProduct->id) }}" method="post" enctype="multipart/form-data" id="attributes_update_form" >
                    @csrf
                    @method('patch')
                    <div class="card-body">
                        {{-- <table id="example1" class="table table-bordered table-striped"> --}}
                        <table id="example1" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Action</th>
                                    <th>Size</th>
                                    <th>SKU</th>
                                    <th>Price</th>
                                    <th>Stock</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($getProduct->attributes as $attribute)    
                                    <tr>
                                        <td>{{ $attribute->id }}</td>
                                        <input type="hidden" name="attributeId[]" id="attributeId" value="{{ $attribute->id}}"/>
                                        <td class="d-flex justify-content-around">
                                            @if ($attribute->status==1)
                                                <a type="button" class="updateAttributeStatus" id="attribute-{{$attribute->id}}"
                                                attribute_id="{{$attribute->id}}" href="javascript:void(0)" title="Inactive"><i class="fas fa-toggle-on" status="Active"></i></a>
                                            @else
                                                <a type="button" class="updateAttributeStatus" id="attribute-{{$attribute->id}}"
                                                attribute_id="{{$attribute->id}}" href="javascript:void(0)" title="Active"><i class="fas fa-toggle-off" status="Inactive" style="color:red"></i></a>
                                            @endif
                                            <a class="confirmDelete" href="javascript:void(0)" recordName="attribute" record="deleteAttribute"  recordId="{{$attribute->id}}" title="Delete Attribute"><i class="far fa-trash-alt"></i></a>
                                        </td>
                                        <td>{{ $attribute->size}}</td>
                                        <td>{{ $attribute->sku}}</td>
                                        <td>
                                            <input type="number" name="price[]" id="price" placeholder="Price" value="{{ $attribute->price}}" style="width: 80px;" required/>
                                        </td>
                                        <td>
                                            <input type="number" name="stock[]" id="stock" placeholder="stock" value="{{ $attribute->stock}}" style="width: 80px;" required/>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>#</th>
                                    <th>Action</th>
                                    <th>Size</th>
                                    <th>SKU</th>
                                    <th>Price</th>
                                    <th>Stock</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-info">Update Attributes</button>
                    </div>
                </form>
            </div>
          <!-- /.card -->
        </div>
        <!-- /.container-fluid -->
    </section>


</div>
  <!-- /.content-wrapper -->
@endsection