routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('admin')->namespace('Admin')->group(function () {
    
    Route::match(['get', 'post'], '/', 'AdminController@login');
    
    Route::group(['middleware'=>['admin']],function () {

        Route::get('dashboard', 'AdminController@index')->name('dashboard');
        Route::get('settings', 'AdminController@settings')->name('settings');
        Route::post('check_current_password', 'AdminController@checkCurrentPassword')->name('checkCurrentPassword');
        Route::post('update-current-password', 'AdminController@updateCurrentPassword')->name('updateCurrentPassword');
        Route::match(['get','post'],'update-admin-details', 'AdminController@updateAdminDetails')->name('updateAdminDetails');

        // Sections Routes
        Route::resource('sections','SectionController');

        // Brands Routes
        Route::resource('brands','BrandsController');
        Route::get('deleteBrand/{id}', 'BrandsController@deleteBrand');
        Route::patch('updateBrandStatus/{id}', 'BrandsController@updateBrandStatus');

        // Categories Routes
        Route::resource('categories', 'CategoriesController');
        Route::patch('categoryStatusUpdate/{id}', 'CategoriesController@categoryStatusUpdate');
        Route::get('getCategoryBySectionId/{id}', 'CategoriesController@getCategoryBySectionId');
        Route::get('getCategoryBySectionIdForProduct/{id}', 'CategoriesController@getCategoryBySectionIdForProduct');
        Route::get('deleteCategory/{id}', 'CategoriesController@deleteCategory');
        Route::get('deleteCategoryImage/{id}', 'CategoriesController@deleteCategoryImage');
        
        // Product Routes
        Route::resource('products', 'ProductsController');
        Route::patch('productStatusUpdate/{id}', 'ProductsController@productStatusUpdate');
        Route::get('getCategoriesBySectionId/{id}', 'ProductsController@getCategoriesBySectionId');
        Route::get('deleteProductMainImage/{id}', 'ProductsController@deleteProductMainImage');
        Route::get('deleteProductVideo/{id}', 'ProductsController@deleteProductVideo');
        Route::get('deleteProduct/{id}', 'ProductsController@deleteProduct');
        
        // Attributes Routes
        Route::resource('attributes', 'ProductAttributesController');
        Route::patch('updateAttributeStatus/{id}', 'ProductAttributesController@updateAttributeStatus');
        Route::get('deleteAttribute/{id}', 'ProductAttributesController@deleteAttribute');

        // Product Images Routes
        Route::resource('productImages', 'ProductImagesController');
        Route::patch('updateProductImageStatus/{id}', 'ProductImagesController@updateProductImageStatus');
        Route::get('deleteProductImage/{id}', 'ProductImagesController@deleteProductImage');

        Route::get('logout', 'AdminController@logout')->name('logout');
        
    });
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = [
        'parent_id', 'section_id', 'name', 'image',
        'discount', 'description', 'url', 'meta_title',
        'meta_description', 'meta_keywords', 'status'
    ];

    public function sub_categories()
    {
        return $this->hasMany(Category::class, 'parent_id')->where('status',1);
    }

    public function section()
    {
        return $this->belongsTo(Section::class, 'section_id')->select('id','name')->where('status',1);
    }
    public function parentCategory()
    {
        return $this->belongsTo(Category::class, 'parent_id')->select('id','name')->where('status',1);
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Section;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Session;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Session::put('page','categories');
        $categories = Category::with(['section','parentCategory'])->where('status',1)->get();
        // $categories = json_decode(json_encode($categories),true);
        // echo "<pre>"; print_r($categories); die;
        return view('admin.categories.categories')->with(compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $sections   =   Section::where('status',1)->get();
        // $categories =   Category::with('sub_categories')->select('id','name')->where('parent_id',0)->where('status',1)->get();
        return view('admin.categories.create_category')->with(compact('sections'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // echo "<pre>"; print_r($request->all()); die;
        $detailsRuls= [
            'name' => 'required|max:255',
            'section_id' => 'required',
            'url' => 'required|max:255',
            'image' => 'image|mimes:jpg,jpeg,png',
        ];
        $customMessage  =   [
            'name.required' => 'Name is required',
        ];
        $this->validate($request, $detailsRuls, $customMessage);
        
        // image update
        $isImageFileHave = 0;
        $newFileName = '';
        $fullPath = '';
        $fileLocation = 'images/category_images/';

        if($request->hasFile('image')){

            
            //! get File Name
            $newImageName = request()->file('image')->getClientOriginalName();
    
            //! remove extension from file name
            // $onlyNewImageName = strtok($newImageName, ".");

            //! get file Extension
            $fileExName = request()->file('image')->getClientOriginalExtension();

            //! better approch for file naming with uniqid() fuction
            // $newFileName = $onlyNewImageName."_".uniqid().".".$fileExName;
            $newFileName = "Category_".uniqid().".".$fileExName;

            //? //* Path with File Name
            $fullPath = $fileLocation.$newFileName;

            // $resizedImage = Image::make($imageFile)->fit(590,708);
            request()->file('image')->move($fileLocation, $newFileName);

            $isImageFileHave = 1;

            //! Image Resize after stored image
            // $image = Image::make($fullPath)->fit(590,708, "top");
            // $image->save();
            $image = Image::make($fullPath)->fit(500, 750, function ($constraint) {
                //$constraint->aspectRatio();
                $constraint->upsize();
            }, "top");
            $image->save();
        }

        $insertData = Category::create([
            'parent_id' => $request->parent_id,
            'section_id' => $request->section_id,
            'name' => $request->name,
            'image' => $isImageFileHave==1?$newFileName:'',
            'discount' => $request->discount==''?0:$request->discount,
            'description' => $request->description,
            'url' => $request->url,
            'meta_title' => $request->meta_title,
            'meta_description' => $request->meta_description,
            'meta_keywords' => $request->meta_keywords,
        ]);
        
        return redirect()->back()->with('success_message', 'New category added successfully done.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // echo '<pre>'; print_r($id); die;
        $getCategries = Category::with('sub_categories')->where('section_id',$id)->where('parent_id',0)->where('status',1)->get();
        if($getCategries){
            $getCategries = json_decode(json_encode($getCategries),true);
            // echo '<pre>'; print_r($getCategries); die;
            return view('admin.categories.append_categories_level')->with(compact('getCategries'));
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $getCategory = Category::where('id',$id)->first();
        $categories = Category::with('sub_categories')->select('id','name')->where('section_id',$getCategory->section_id)->where('parent_id',0)->where('status',1)->get();
        $sections   = Section::where('status',1)->get();
        if($getCategory){
            // $categories = json_decode(json_encode($categories),true);
            // echo '<pre>'; print_r($categories); die;
            return view('admin.categories.edit_category')->with(compact('getCategory','categories','sections'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // echo '<pre>'; print_r($id); die;
        $getCategory    =   Category::find($id);

        $detailsRuls= [
            'name' => 'required|max:255',
            'section_id' => 'required',
            'url' => 'required|max:255',
            'image' => 'image|mimes:jpg,jpeg,png',
        ];
        $customMessage  =   [
            'name.required' => 'Name is required',
        ];
        $this->validate($request, $detailsRuls, $customMessage);
        
        // image update
        $imageName = $getCategory->image;
        $isImageFileHave = 0;
        $newFileName = '';
        $fullPath = '';
        $fileLocation = 'images/category_images/';

        if($request->hasFile('image')){

            if($getCategory->image != '' || $getCategory->image != 'null'){
                
                
                $fullPath = $fileLocation.$imageName;
    
                if(\File::exists($fullPath)){
        
                    \File::delete($fullPath);
                }

                //! get File Name
                $newImageName = request()->file('image')->getClientOriginalName();

                //! remove extension from file name
                // $onlyNewImageName = strtok($newImageName, ".");

                //! get file Extension
                $fileExName = request()->file('image')->getClientOriginalExtension();

                //! better approch for file naming with uniqid() fuction
                // $newFileName = $onlyNewImageName."_".uniqid().".".$fileExName;
                $newFileName = "Category_".uniqid().".".$fileExName;

                //? //* Path with File Name
                $fullPath = $fileLocation.$newFileName;

                // $resizedImage = Image::make($imageFile)->fit(590,708);
                request()->file('image')->move($fileLocation, $newFileName);

                $getCategory->update([
                    'image' => $newFileName,
                ]);

                //! Image Resize after stored image
                // $image = Image::make($fullPath)->fit(590,708, "top");
                // $image->save();
                // resize the image so that the largest side fits within the limit; the smaller
                // side will be scaled to maintain the original aspect ratio
                $image = Image::make($fullPath)->fit(300, 300, function ($constraint) {
                    //$constraint->aspectRatio();
                    $constraint->upsize();
                }, "top");
                $image->save();


            }else{
                //! get File Name
                $newImageName = request()->file('image')->getClientOriginalName();
        
                //! remove extension from file name
                // $onlyNewImageName = strtok($newImageName, ".");

                //! get file Extension
                $fileExName = request()->file('image')->getClientOriginalExtension();

                //! better approch for file naming with uniqid() fuction
                // $newFileName = $onlyNewImageName."_".uniqid().".".$fileExName;
                $newFileName = "Category_".uniqid().".".$fileExName;

                //? //* Path with File Name
                $fullPath = $fileLocation.$newFileName;

                // $resizedImage = Image::make($imageFile)->fit(590,708);
                request()->file('image')->move($fileLocation, $newFileName);

                $getCategory->update([
                    'image' => $newFileName,
                ]);

                //! Image Resize after stored image
                // $image = Image::make($fullPath)->fit(590,708, "top");
                // $image->save();
                $image = Image::make($fullPath)->fit(500, 750, function ($constraint) {
                    //$constraint->aspectRatio();
                    $constraint->upsize();
                }, "top");

                $image->save();
            }
        }

        $getCategory->update([
            'parent_id' => $request->parent_id,
            'section_id' => $request->section_id,
            'name' => $request->name,
            'discount' => $request->discount==''?0:$request->discount,
            'description' => $request->description,
            'url' => $request->url,
            'meta_title' => $request->meta_title,
            'meta_description' => $request->meta_description,
            'meta_keywords' => $request->meta_keywords,
        ]);
        

resources/views/admin/categories/append_categories_level.blade.php
<div class="form-group">
    <label for="parent_id">Category Level*</label>
    <select class="form-control select2" id="parent_id" style="width: 100%;" name="parent_id" required>
        <option selected="selected" value="0">Root Category</option>
        @if (!empty($getCategries))    
            @foreach ($getCategries as $category)
                <option value="{{$category['id']}}">{{$category['name']}}</option>
                @if (!empty($category['sub_categories']))    
                    @foreach ($category['sub_categories'] as $subCategory)
                        <option value="{{$subCategory['id']}}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&gt;&nbsp;{{$subCategory['name']}}</option>
                    @endforeach
                @endif
            @endforeach
        @endif
    </select>
</div>

resources/views/admin/categories/create_category.blade.php
@extends('layouts.Admin.admin_layout')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Catalogues</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ url('admin/dashboard') }}">Home</a></li>
              <li class="breadcrumb-item active">Add Category</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- SELECT2 EXAMPLE -->
            <div class="card card-default">
                <div class="card-header">
                    <h3 class="card-title">New Category</h3>
                    <a href="{{route('categories.index')}}" class="btn btn-block btn-primary" style="max-width: 150px; float: right;">All Categories</a>
                    {{-- <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove">
                            <i class="fas fa-times"></i>
                        </button>
                    </div> --}}
                </div>
                <div>
                    @if (session('success_message'))
                        {{-- <div class="alert alert-success" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <strong>Success!</strong> You have been signed in successfully!
                        </div> --}}
                        <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 5px;">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            {{session('success_message')}}
                        </div>
                        @endif
                        {{-- Successful Message Alert with close and fade effect from controller --}}
                        @if (session('error_message'))
                        {{-- <div class="alert alert-success" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <strong>Success!</strong> You have been signed in successfully!
                        </div> --}}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            {{session('error_message')}}
                        </div>
                        @endif
                
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                </div>
                <!-- /.card-header -->
                <form action="{{ route('categories.store') }}" method="post" enctype="multipart/form-data" id="category_form">
                    @csrf
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="section_id">Sections*</label>
                                    <select class="form-control select2" style="width: 100%;" name="section_id" id="section_id" required>
                                        <option selected="selected">Select Section</option>
                                        @foreach ($sections as $section)
                                            <option value="{{$section->id}}">{{$section->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="name">Category Name*</label>
                                    <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}" placeholder="Enter Category Name" required>
                                </div>
                                <div class="form-group">
                                    <label for="discount">Category Discount(%)</label>
                                    <input type="text" class="form-control" id="discount" name="discount" placeholder="Enter Category Discount">
                                </div>
                                <div class="form-group">
                                    <label for="description">Category Description</label>
                                    <textarea class="form-control" rows="2" placeholder="Enter Description" id="description" name="description">{{ old('description') }}</textarea>
                                </div>
                                <div class="form-group">
                                    <label for="meta_description">Meta Description</label>
                                    <textarea class="form-control" rows="2" placeholder="Enter Meta Description" id="meta_description" name="meta_description">{{ old('meta_description') }}</textarea>
                                </div>
                            </div>
                            <!-- /.col -->
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="parent_id">Category Level*</label>
                                    <select class="form-control select2" id="parent_id" style="width: 100%;" name="parent_id" required>
                                        <option selected="selected" value="0" disabled>Root Category</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="image">Category Image</label>
                                    <div class="input-group">
                                      <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="image" name="image" accept="image/*">
                                        <label class="custom-file-label" for="image">Choose image</label>
                                      </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="url">Category URL*</label>
                                    <input type="text" class="form-control" id="url" name="url" value="{{ old('url') }}" placeholder="Enter Category URL" required>
                                </div>
                                <div class="form-group">
                                    <label for="meta_title">Meta Title</label>
                                    <textarea class="form-control" rows="2" placeholder="Enter Meta Title" id="meta_title" name="meta_title">{{ old('meta_title') }}</textarea>
                                </div>
                                <div class="form-group">
                                    <label for="meta_keywords">Meta Keywords</label>
                                    <textarea class="form-control" rows="2" placeholder="Enter Meta Keywords" id="meta_keywords" name="meta_keywords">{{ old('meta_keywords') }}</textarea>
                                </div>
                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- /.row -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <button type="submit" class="btn btn-success btn-block">Submit</button>
                    </div>
                </form>
            </div>
          <!-- /.card -->
        </div>
        <!-- /.container-fluid -->
    </section>


</div>
  <!-- /.content-wrapper -->
@endsection